### ISSUE TITLE
Ability to toggle notfications.

### ISSUE THREAD

**Issue by sina158** [markusfisch/ScreenTime#16]
recommendation to further improve the application . the application will have a permeant notification showing the 
progress of your screen time ,believe that it is better for that to be users choice .

I have gathered the reviews and data from this app and similar apps. with these reviews cleaned and analyzed using elevated topic models i have determined that his functionality is appreciated by other users in competitor applications

**Comment by markusfisch** [comment]
The notification is necessary to keep the app running in the background. Without it, the app would be killed by the system 🤷‍♂️ 

But since this app was designed with the sole purpose of showing just the screen time in a permanent notification, this is not a problem. If you don't want to see the notification, you probably don't need this app 😉
