### ISSUE TITLE
Screen saver mode is being counted as screen time

### ISSUE THREAD

**Issue by Anonymous1157** [markusfisch/ScreenTime#9]
Hi! I enabled a screen saver during charging on my device, and now Screen Time thinks I was active when the device was actually not in use but displaying the screen saver. Would it be possible not to count the time the screen is turned on for a screen saver while charging?

**Comment by markusfisch** [comment]
Hm, well, probably 🤔 

It's a bit unexpected because the app is counting when the system sends an [ACTION_USER_PRESENT](https://developer.android.com/reference/android/content/Intent#ACTION_USER_PRESENT) broadcast - which clearly isn't the case when a screen saver is running 😉 

Now, I see that there's also an [ACTION_DREAMING_STARTED](https://developer.android.com/reference/android/content/Intent.html#ACTION_DREAMING_STARTED) broadcast I could catch so it should be possible to detect when the screen saver is on. Will try…

In any case a good catch! Thanks for filing an issue about that 👍

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/ScreenTime/commit/ad19ad74b51dadbf2f9994d612ccb0e578750e95

It's in version 1.1.1 which should soon become available on Google Play:
https://github.com/markusfisch/ScreenTime/releases/tag/1.1.1

**Comment by Anonymous1157** [comment]
I got the update on my devices using F-Droid and it appears to be working! Unfortunately this change broke backwards compatibility, and the new version crashes on an older device with Android 4.1 that I keep around for experimentation but don't really use anymore.

Personally I think it would be acceptable to drop support for old Android versions, but is it possible to bump the min SDK retroactively in the 1.1.1 release so that F-Droid will not try to download it on incompatible devices?

**Comment by markusfisch** [comment]
Sorry for the crash 🙈 I really should've checked it on Android 4.x before releasing. Unfortunately I can't do another release before next week. But it 's really to fix, and I'll fix it as soon as possible. Thanks a lot for reporting this 👍Changing the minSdk after releasing isn't possible, unfortunately.About the support for old Android's, I really like to support them as far back as it's easily possible. I don't like leaving someone behind just because his/her phone is old. Or just because it would be easier for me to drop support 😉 Am 21.06.2022 19:23 schrieb Anonymous1157 ***@***.***>:
I got the update on my devices using F-Droid and it appears to be working! Unfortunately this change broke backwards compatibility, and the new version crashes on an older device with Android 4.1 that I keep around for experimentation but don't really use anymore.
Personally I think it would be acceptable to drop support for old Android versions, but is it possible to bump the min SDK retroactively in the 1.1.1 release so that F-Droid will not try to download it on incompatible devices?
